#pragma once

// Forward declarations for web, MQTT, update and logic handlers.
static bool web_require_auth();
static void sample_cpu_load();
static const char * module_type_name(uint8_t type);
static String json_escape(const char* s);
static String current_master_ip_string();
static String uid_hex(uint64_t uid);
static String module_label_key(uint64_t uid);
static String module_snapshot_key(uint8_t index, char suffix);
static void load_module_snapshot();
static void save_module_snapshot();
static String clean_module_label(String label);
static String clean_io_alias(String label);
static String module_label_for(const ModuleRecord& m);
static String module_display_name(const ModuleRecord& m);
static void apply_module_labels();
static String bytes_hex(const uint8_t* data, uint8_t len);
static String bytes_ascii(const uint8_t* data, uint8_t len);
static String duration_text_minutes(uint32_t minutes);
static String duration_text_seconds(uint32_t seconds);
static String jbc_error_text(uint16_t mask);
static String output_fault_text(uint16_t mask);
static String output_fault_text_for_module(uint16_t mask, uint8_t module_type);
static const char * station_type_name(uint8_t addr);
static MasterAlarmJson build_master_alarm_json();
static String html_escape(const String& in);
static String build_state_json(bool include_universal_descriptor = false, bool include_heap_diag = false);
static String normalized_hostname(String value);
static bool parse_ipv4(const String& text, IPAddress& value);
static void build_master_hostname();
static void netcfg_load();
static bool netcfg_save(const String& ssid, const String& pass, const String& hostname, const String& web_user_arg, const String& web_pass_arg, bool use_static, const IPAddress& ip, const IPAddress& gateway, const IPAddress& subnet, const IPAddress& dns1, const IPAddress& dns2, bool mqtt_en, bool mqtt_tls, const String& mqtt_host_arg, uint16_t mqtt_port_arg, const String& mqtt_user_arg, const String& mqtt_pass_arg, const String& mqtt_topic_arg, bool mqtt_ha, const String& mqtt_disc_arg, const String& mqtt_ca_arg, bool led_en, uint8_t led_pct);
static void apply_status_led_config();
static bool save_status_led_config(bool enabled, uint8_t brightness_pct);
static void netcfg_reset();
static void webauth_reset();
static void serial_cli_prompt();
static void serial_cli_print_help();
static void serial_cli_print_status();
static void serial_cli_print_modules();
static void serial_cli_print_module(uint8_t addr);
static void serial_cli_print_routes();
static void serial_cli_print_bus();
static void serial_cli_print_mqtt();
static void serial_cli_print_network();
static void serial_cli_execute(String command);
static void serial_cli_tick();
static void serial_cli_task(void* parameter);
static void web_service_task(void* parameter);
static void wifi_service_tick();
static void ui_config_load();
static void web_handle_state();
static void web_handle_led_state();
static String mqtt_topic_path(const char* leaf);
static String mqtt_discovery_topic(const char* component, const char* object, const char* suffix);
static String mqtt_config_url();
static String mqtt_device_json();
static String mqtt_module_device_json(const ModuleRecord& m);
static const char * mqtt_suction_name(uint8_t level);
static const char * mqtt_state_text(int state);
static void mqtt_publish_discovery_control(const char* component, const char* suffix, const char* name, const char* value_template, const char* command_leaf, const char* extra_json);
static String mqtt_module_topic(uint8_t addr, const char* leaf);
static String mqtt_module_command_leaf(uint8_t addr, const char* action);
static String mqtt_fw_string(const ModuleRecord& m);
static const char * mqtt_weller_filter_text(uint8_t status);
static String mqtt_unavailable_route_label(const char* de, const char* en, uint8_t addr);
static bool mqtt_has_online_jbc_modules();
static String mqtt_main_input_label(uint8_t source_type, uint8_t source_addr, uint8_t source_bit);
static String mqtt_main_output_unavailable_label(uint8_t addr = 0);
static String mqtt_main_output_label(uint8_t addr);
static bool mqtt_parse_universal_descriptor_line(const char* line, MqttUniversalEntityDef& out);
static uint8_t mqtt_sorted_module_indices(uint8_t* order, uint8_t max_count);
static bool mqtt_registry_has_addr(uint8_t addr);
static String mqtt_module_discovery_signature_now();
static void mqtt_publish_discovery_custom(const char* component, const char* suffix, const char* name, const String& state_topic, const char* value_template, const String& command_topic, const char* extra_json);
static void mqtt_publish_module_entity(const ModuleRecord& m, const char* component, const char* suffix, const String& name, const char* value_template, const char* extra_json, const String& command_leaf, bool stateful);
static void mqtt_publish_module_discovery(const ModuleRecord& m);
static void mqtt_clear_module_entity(uint8_t addr, const char* component, const char* suffix);
static void mqtt_clear_module_state(uint8_t addr);
static void mqtt_cleanup_tick();
static void mqtt_publish_discovery();
static bool mqtt_payload_bool(const String& value);
static void mqtt_apply_command(const String& leaf, const String& value);
static void mqtt_callback(char* topic, uint8_t* payload, unsigned int length);
static bool mqtt_config_ready();
static bool mqtt_ca_looks_valid();
static void mqtt_configure_client();
static bool mqtt_connect_if_needed();
static bool mqtt_mask_bit(uint16_t mask, uint8_t bit);
static const char * mqtt_display_language_text(uint8_t language);
static const char * mqtt_display_theme_text(uint8_t theme);
static const char * mqtt_display_screensaver_text(uint8_t minutes);
static uint8_t mqtt_display_screensaver_value(const String& value);
static void mqtt_publish_module_state(const ModuleRecord& m);
static void mqtt_publish_module_offline(uint8_t addr);
static void mqtt_publish_all_availability_offline();
static void mqtt_loop();
static void web_handle_diagnostics();
static void web_handle_diagnostics_state();
static void web_handle_diagnostics_events();
static void web_handle_diagnostics_control();
static void web_handle_logic();
static void web_handle_logic_json();
static void web_handle_logic_list();
static void web_handle_logic_select();
static void web_handle_logic_new();
static void web_handle_logic_delete();
static void web_handle_logo();
static void web_handle_scan();
static void web_handle_module_label();
static void web_handle_io_alias();
static void web_handle_jbc_usb_station_name();
static void web_handle_jbc_usb_config();
static bool web_is_german();
static const char * web_text(const char* de, const char* en);
static String json_get_string_field(const String& src, const char* key, const String& fallback);
static bool json_get_bool_field(const String& src, const char* key, bool fallback);
static uint32_t json_get_u32_field(const String& src, const char* key, uint32_t fallback);
static String web_csrf_script();
static void web_shell_begin(String& html, const char* title, const char* section, const char* active_page);
static void web_shell_end(String& html);
static void web_handle_update();
static void web_handle_master_update_done();
static void web_handle_master_update_upload();
static void master_update_abort_active();
static void web_handle_master_chunk_begin();
static void web_handle_master_chunk_done();
static void web_handle_master_chunk_upload();
static void web_handle_master_chunk_end();
static void web_handle_master_chunk_abort();
static bool module_update_abort_active();
static void module_update_queue_reset();
static bool module_update_queue_push(const uint8_t* data, size_t len, uint32_t timeout_ms);
static void module_update_pump();
static void module_update_io_init();
static uint8_t module_update_fw_chunk_size(uint8_t addr);
static bool module_update_wait_sent(uint32_t target_offset, uint32_t timeout_ms);
static void web_handle_module_chunk_abort();
static void web_handle_module_update_done();
static uint8_t module_update_target_from_request();
static const char* module_firmware_hint(uint8_t type);
static bool module_firmware_filename_allowed(uint8_t type, const String& filename);
static bool module_update_target_allowed(uint8_t addr, const String& filename = String());
static void web_handle_module_chunk_begin();
static void web_handle_module_chunk_done();
static void web_handle_module_chunk_upload();
static void web_handle_module_chunk_end();
static void web_handle_module_update_stats();
static void web_handle_module_update_upload();
static void web_redirect_config();
static void web_handle_config();
static void web_handle_config_export();
static void web_handle_config_import();
static void web_handle_config_leds();
static void web_handle_config_mqtt();
static void web_handle_config_save();
static void web_handle_not_found();
static uint16_t web_arg_u16(const char* name, uint16_t fallback, uint16_t max_value);
static uint16_t customPowerFromSelectFlow(uint16_t select_flow);
static String route_key(uint8_t addr, uint8_t bit);
static String rule_key(uint8_t index, const char* suffix);
static void load_input_action_rules();
static void logic_runtime_tick();
static void save_input_action_rule(uint8_t index, const MasterScheduler::InputActionRule& rule);
static void web_handle_jbc_settings();
static void web_handle_io_set();
static void web_handle_module_output_set();
static void web_handle_fanio_calibration();
static void web_handle_weller_set();
static void web_handle_display_set();
static void web_handle_universal_profile();
static void web_handle_universal_profile_read();
static void web_handle_universal_entity();
static void web_handle_main_input_select();
static void web_handle_output_select();
static void web_handle_routing_set();
static void web_handle_routing_rule();
static void web_handle_language_set();
static void web_handle_module_reboot();
static void prepare_controlled_restart();
static void web_handle_restart();
static void web_handle_root();
static void web_handle_developer_mode();
static void heap_diag_enable();
