#pragma once

// Arduino's .ino preprocessor may emit autogenerated function prototypes
// before type declarations that appear later in the sketch.  Several profile
// helper functions take ProfileEntity by reference, so make the type visible
// from an included header before prototype generation happens.
struct ProfileEntity;
